import { StyleSheet } from "react-native";
import { THEME } from "../../../theme";

export const alertDetailsStyles = StyleSheet.create({
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
  },
  stateText: {
    color: THEME.textMuted,
    fontWeight: "600",
    fontSize: 14,
  },
  errorTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: THEME.primary,
  },
  errorBody: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  primaryButtonSmall: {
    marginTop: 12,
    backgroundColor: THEME.accent,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  primaryButtonText: {
    color: THEME.primary,
    fontWeight: "800",
    fontSize: 15,
  },
  detailPage: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 32,
  },
  detailHeroCard: {
    backgroundColor: THEME.primary,
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
  },
  detailHeroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  detailHiveIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 14,
    backgroundColor: "rgba(255,178,104,0.15)",
    borderWidth: 1,
    borderColor: "rgba(255,178,104,0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  detailHeroTextWrap: { flex: 1 },
  detailHiveName: {
    fontSize: 20,
    fontWeight: "800",
    color: THEME.surface,
    marginBottom: 3,
  },
  detailHeroMeta: {
    fontSize: 12,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "500",
  },
  alertClosedBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 12,
    backgroundColor: "#F0FDF4",
    borderRadius: 8,
    padding: 8,
  },
  alertClosedText: {
    fontSize: 12,
    color: "#16A34A",
    fontWeight: "600",
    flex: 1,
  },
  severityPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  severityPillText: {
    fontWeight: "800",
    fontSize: 12,
  },
  card: {
    backgroundColor: THEME.surface,
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: THEME.primary,
    marginBottom: 2,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: THEME.line,
  },
  infoLabel: {
    color: "#667085",
    fontWeight: "700",
  },
  infoValue: {
    fontWeight: "800",
  },
  detailLongText: {
    fontSize: 13,
    color: THEME.text,
    lineHeight: 20,
  },
  advisoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  advisoryTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  advisoryTypeBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  advisoryTypeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  advisorySummary: {
    fontSize: 13,
    color: THEME.textMuted,
    lineHeight: 19,
    marginBottom: 14,
  },
  advisoryActionsTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: THEME.text,
    marginBottom: 10,
  },
  advisoryActionRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: THEME.line,
  },
  advisoryActionText: {
    fontSize: 13,
    color: THEME.text,
    lineHeight: 18,
  },
  advisoryPriorityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginTop: 5,
  },
  audioHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  audioSubtext: {
    fontSize: 12,
    color: THEME.textMuted,
    marginBottom: 4,
  },
  audioControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 12,
  },
  audioButton: {
    backgroundColor: THEME.accent,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    justifyContent: "center",
  },
  audioButtonPlaying: {
    backgroundColor: "#D97706",
  },
  audioButtonText: {
    color: THEME.surface,
    fontWeight: "700",
    fontSize: 14,
  },
  audioButtonSecondary: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: THEME.accent,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  audioButtonSecondaryText: {
    color: THEME.accent,
    fontWeight: "700",
    fontSize: 14,
  },
});
