import { StyleSheet } from "react-native";
import { THEME } from "../../theme";

export const dashboardStyles = StyleSheet.create({
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
  },
  stateText: {
    color: THEME.textMuted,
    fontWeight: "600",
    fontSize: 14,
  },
  errorTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: THEME.primary,
  },
  errorBody: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  primaryButtonSmall: {
    marginTop: 12,
    backgroundColor: THEME.accent,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  primaryButtonText: {
    color: THEME.primary,
    fontWeight: "800",
    fontSize: 15,
  },
  appPage: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 32,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#344054",
    marginBottom: 10,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: THEME.primary,
    marginBottom: 2,
  },
  cardSubtitle: {
    fontSize: 11,
    color: THEME.textMuted,
    fontWeight: "600",
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  gridTwo: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 10,
    columnGap: 0,
    marginBottom: 14,
  },
  // ── Dashboard alert card ──
  dashboardAlertsCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  dashboardAlertsTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  dashboardAlertsTitleWrap: { flex: 1 },
  dashboardAlertsTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: THEME.primary,
  },
  dashboardAlertsSubTitle: {
    fontSize: 11,
    color: THEME.textMuted,
    fontWeight: "600",
    marginTop: 2,
  },
  hiveAlertCountBadge: {
    backgroundColor: THEME.surfaceSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: THEME.line,
  },
  hiveAlertCountText: {
    fontSize: 11,
    fontWeight: "700",
    color: THEME.textMuted,
  },
  dashboardAlertMenuRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  dashboardAlertMenuChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#FFFFFF",
  },
  dashboardAlertMenuChipActive: {
    backgroundColor: THEME.primary,
    borderColor: THEME.primary,
  },
  dashboardAlertMenuChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: THEME.primary,
  },
  dashboardAlertMenuChipTextActive: {
    color: "#FFFFFF",
  },
  dashboardAlertSubMenu: {
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 12,
    backgroundColor: "#FAFAFA",
    padding: 10,
    marginBottom: 8,
    gap: 8,
  },
  dashboardAlertSubMenuHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dashboardAlertSubMenuTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: THEME.primary,
  },
  dashboardAlertSubMenuCloseBtn: {
    padding: 4,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: THEME.line,
  },
  dashboardAlertSubMenuList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  dashboardAlertSubMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  dashboardAlertSubMenuItemActive: {
    borderColor: THEME.primary,
    backgroundColor: THEME.surfaceSoft,
  },
  dashboardAlertSubMenuItemText: {
    fontSize: 11,
    fontWeight: "700",
    color: THEME.text,
    maxWidth: 160,
  },
  dashboardAlertSubMenuItemTextActive: {
    color: THEME.primary,
  },
  dashboardAlertSubMenuDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  dashboardAlertSubMenuEmpty: {
    fontSize: 11,
    color: THEME.textMuted,
    fontWeight: "600",
  },
  dashboardAlertsInlineError: {
    marginTop: 8,
    fontSize: 11,
    color: "#B91C1C",
    fontWeight: "600",
  },
  dashboardAlertScroller: {
    marginTop: 10,
    gap: 8,
    paddingRight: 4,
  },
  dashboardAlertCompactCard: {
    width: 165,
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    padding: 10,
    gap: 5,
  },
  dashboardAlertCompactCardActive: {
    borderColor: THEME.primary,
    backgroundColor: THEME.surfaceSoft,
  },
  dashboardAlertCompactTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  dashboardAlertCompactDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  dashboardAlertCompactHive: {
    fontSize: 10,
    fontWeight: "700",
    color: THEME.textMuted,
  },
  dashboardAlertCompactTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: THEME.primary,
  },
  dashboardAlertCompactDate: {
    fontSize: 10,
    color: THEME.textMuted,
    fontWeight: "600",
  },
  dashboardAlertsEmptyState: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#BBF7D0",
    backgroundColor: "#F0FDF4",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dashboardAlertsEmptyStateText: {
    fontSize: 11,
    color: "#166534",
    fontWeight: "700",
  },
  dashboardAlertDetailsCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    padding: 12,
    gap: 5,
  },
  dashboardAlertDetailsTitle: {
    flex: 1,
    marginRight: 8,
    fontSize: 14,
    fontWeight: "800",
    color: THEME.primary,
  },
  dashboardAlertDetailsSeverity: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  dashboardAlertDetailsSeverityText: {
    fontSize: 11,
    fontWeight: "800",
  },
  dashboardAlertDetailsMeta: {
    fontSize: 11,
    fontWeight: "600",
    color: THEME.textMuted,
  },
  dashboardAlertDetailsSummary: {
    fontSize: 12,
    lineHeight: 18,
    color: THEME.text,
  },
  dashboardAlertDetailsLink: {
    marginTop: 4,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 999,
    backgroundColor: THEME.surfaceSoft,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  dashboardAlertDetailsLinkText: {
    fontSize: 11,
    fontWeight: "800",
    color: THEME.primary,
  },
  // ── Overview tiles ──
  overviewCardRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  overviewTile: {
    flex: 1,
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    gap: 4,
  },
  overviewTileValue: {
    fontSize: 20,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  overviewTileLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: "rgba(255,255,255,0.8)",
    textAlign: "center",
  },
  // ── Donut ──
  donutRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    paddingTop: 8,
  },
  donutLegend: {
    flex: 1,
    gap: 8,
  },
  donutLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  donutLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  donutLegendLabel: {
    flex: 1,
    fontSize: 12,
    color: THEME.text,
    fontWeight: "600",
  },
  donutLegendCount: {
    fontSize: 13,
    fontWeight: "800",
    color: THEME.primary,
  },
  // ── Trend range ──
  trendRangeRow: {
    flexDirection: "row",
    gap: 4,
  },
  trendRangeBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: THEME.line,
    backgroundColor: THEME.surface,
  },
  trendRangeBtnActive: {
    backgroundColor: THEME.accent,
    borderColor: THEME.accent,
  },
  trendRangeBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: THEME.textMuted,
  },
  trendRangeBtnTextActive: {
    color: "#FFFFFF",
  },
  // ── Metric / Stat cards ──
  statCard: {
    width: "49%",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 12,
    padding: 12,
  },
  statLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 6,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: THEME.accent,
  },
  statValue: {
    fontSize: 28,
    color: THEME.primary,
    fontWeight: "800",
  },
  metricCard: {
    width: "49%",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 12,
    padding: 12,
  },
  metricTitle: {
    fontSize: 12,
    color: THEME.accent,
    fontWeight: "700",
    marginBottom: 8,
  },
  metricValue: {
    fontSize: 32,
    color: THEME.primary,
    fontWeight: "800",
  },
  metricUnit: {
    fontSize: 16,
    color: THEME.primary,
    fontWeight: "700",
  },
  metricSubtitle: {
    fontSize: 11,
    color: "#9AA6B5",
    marginTop: 6,
  },
  // ── Info cards ──
  infoCard: {
    width: "49%",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: THEME.line,
    borderRadius: 12,
    padding: 12,
    gap: 4,
  },
  infoCardWarn: {
    borderColor: "#FCA5A5",
    backgroundColor: "#FFF5F5",
  },
  infoCardValue: {
    fontSize: 26,
    fontWeight: "800",
    color: THEME.primary,
  },
  infoCardLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: THEME.text,
  },
  infoCardSub: {
    fontSize: 10,
    color: THEME.textMuted,
  },
  // ── Silent hives ──
  silentHivesList: {
    backgroundColor: "#FFF5F5",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FCA5A5",
    padding: 10,
    gap: 8,
    marginBottom: 14,
  },
  silentHiveRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  silentHiveText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    color: THEME.text,
  },
  silentHiveTime: {
    fontSize: 11,
    color: "#EF4444",
    fontWeight: "600",
  },
  // ── Correlation ──
  corrRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  },
  corrHiveChip: {
    backgroundColor: THEME.surfaceSoft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 72,
  },
  corrHiveChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: THEME.primary,
  },
  corrTempBar: {
    flex: 1,
    height: 8,
    backgroundColor: "#F1F5F9",
    borderRadius: 99,
    overflow: "hidden",
  },
  corrTempFill: {
    height: "100%",
    backgroundColor: "#D97706",
    borderRadius: 99,
  },
  corrTempValue: {
    fontSize: 12,
    fontWeight: "700",
    color: THEME.primary,
    minWidth: 44,
    textAlign: "right",
  },
  // ── Metrics legend ──
  metricsSubtitle: {
    color: "#667085",
    fontWeight: "600",
    fontSize: 12,
    marginTop: 2,
    marginBottom: 10,
  },
  metricsLegendRow: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 8,
  },
  metricsLegendItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 10,
    marginRight: 8,
  },
  legendText: {
    color: "#475467",
    fontWeight: "600",
  },
});
