import { StyleSheet } from "react-native";
import { THEME } from "../../theme";

export const profileStyles = StyleSheet.create({
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
  },
  stateText: {
    color: THEME.textMuted,
    fontWeight: "600",
    fontSize: 14,
  },
  profilePage: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 32,
    gap: 12,
  },
  profileHeroCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: THEME.line,
    gap: 8,
  },
  profileAvatarCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: THEME.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  profileAvatarInitials: {
    color: THEME.accent,
    fontSize: 26,
    fontWeight: "800",
  },
  profileHeroName: {
    fontSize: 20,
    fontWeight: "800",
    color: THEME.primary,
  },
  profileHeroRole: {
    fontSize: 13,
    color: THEME.textMuted,
    fontWeight: "600",
  },
  profileNameInput: {
    fontSize: 18,
    fontWeight: "700",
    color: THEME.primary,
    borderBottomWidth: 2,
    borderBottomColor: THEME.accent,
    paddingBottom: 4,
    textAlign: "center",
    width: "100%",
  },
  profileSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: THEME.line,
    padding: 14,
  },
  profileSectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: THEME.primary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 12,
  },
  profileFieldRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 4,
  },
  profileFieldIcon: {
    marginTop: 2,
  },
  profileFieldLabel: {
    fontSize: 11,
    color: THEME.textMuted,
    fontWeight: "600",
    marginBottom: 2,
  },
  profileFieldValue: {
    fontSize: 14,
    color: THEME.primary,
    fontWeight: "600",
  },
  profileFieldInput: {
    fontSize: 14,
    color: THEME.primary,
    borderBottomWidth: 1,
    borderBottomColor: THEME.line,
    paddingVertical: 4,
  },
  profileDivider: {
    height: 1,
    backgroundColor: THEME.line,
    marginVertical: 10,
  },
  profileActionsRow: {
    flexDirection: "row",
    gap: 10,
  },
  profileSecondaryBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.line,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  profileSecondaryBtnText: {
    color: THEME.text,
    fontWeight: "700",
    fontSize: 13,
  },
  profilePrimaryBtn: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: THEME.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  profilePrimaryBtnText: {
    color: THEME.primary,
    fontWeight: "800",
    fontSize: 13,
  },
  profileEditBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.line,
    backgroundColor: "#FFFFFF",
    paddingVertical: 12,
  },
  profileEditBtnText: {
    color: THEME.primary,
    fontWeight: "700",
    fontSize: 13,
  },
  profileLinkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
  },
  profileLinkText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: THEME.primary,
  },
  profileLogoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FEE2E2",
    backgroundColor: "#FEF2F2",
    paddingVertical: 13,
  },
  profileLogoutText: {
    color: "#B42318",
    fontWeight: "700",
    fontSize: 14,
  },
  profileVersion: {
    textAlign: "center",
    fontSize: 12,
    color: THEME.textMuted,
    fontWeight: "500",
    marginTop: 4,
  },
});
